export default {
  ADD_PAYMENT: "ADD_PAYMENT",
  ADD_PERSON: "ADD_PERSON",
  CHANGE_PAYMENT_VALUE: "SET_PAYMENT_VALUE",
  CHANGE_PERSON_NAME: "SET_PERSON_NAME",
  DELETE_PAYMENT: "DELETE_PAYMENT",
  DELETE_PERSON: "DELETE_PERSON",
  REFRESH_RESULTS: "CALCULATE",
}